# Generated by Django 3.2 on 2021-07-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherscan_app', '0004_auto_20210706_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2000-10-10 10:10'),
            preserve_default=False,
        ),
    ]
