# Generated by Django 3.2 on 2021-07-08 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etherscan_app', '0005_address_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='created_at',
        ),
    ]
