# Generated by Django 3.2 on 2021-07-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherscan_app', '0011_alter_address_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='address',
            name='folders',
            field=models.ManyToManyField(related_name='folders', to='etherscan_app.Folder'),
        ),
    ]
