# Generated by Django 3.2 on 2021-07-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etherscan_app', '0012_auto_20210716_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='folder_name',
            new_name='folder',
        ),
    ]
