# Generated by Django 3.2 on 2021-07-16 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etherscan_app', '0013_rename_folder_name_folder_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='auth.user'),
            preserve_default=False,
        ),
    ]
