# Generated by Django 3.2 on 2021-07-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherscan_app', '0014_folder_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='folder',
            new_name='folder_name',
        ),
        migrations.AlterField(
            model_name='address',
            name='folders',
            field=models.ManyToManyField(related_name='addresses', to='etherscan_app.Folder'),
        ),
    ]
