# Generated by Django 3.2 on 2021-07-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etherscan_app', '0015_auto_20210719_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value_in_ether',
            field=models.DecimalField(decimal_places=20, max_digits=110),
        ),
    ]
