version: '3'
services:
  django:
    build:
      context: .
      dockerfile: docker/Dockerfile
    expose:
      - 8000
    command: gunicorn --bind 0.0.0.0:8000 etherscan_project.wsgi:application
    env_file: .env
    volumes:
    - app-files:/srv/app

  db:
    image: postgres:latest
    expose:
      - 5432
    env_file: .env
    volumes:
      - ./docker/volumes/postgresql:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: nginx:1.13
    ports:
      - 80:80
    depends_on:
    - db
    - django
    volumes:
    - ./docker/nginx:/etc/nginx/conf.d
    - app-files:/srv/app

volumes:
  app-files:
    driver_opts:
      type: nfs
      device: $PWD
      o: bind